const createErroror = require("../utils/createerroror");
exports.createEmployees = async () => {
  try {
  } catch (error) {
    next(error);
  }
};

exports.updateEmployees = async () => {
  try {
  } catch (error) {
    next(error);
  }
};
exports.deleteEmployees = async () => {
  try {
  } catch (error) {
    next(error);
  }
};
