const createError = require("../utils/createError");
exports.createPost = async () => {
  try {
  } catch (error) {
    next(error);
  }
};

exports.updatePost = async () => {
  try {
  } catch (error) {
    next(error);
  }
};
exports.deletePost = async () => {
  try {
  } catch (error) {
    next(error);
  }
};
