const createError = require("../utils/createError");
exports.createSkill = async () => {
  try {
  } catch (error) {
    next(error);
  }
};

exports.deleteSkill = async () => {
  try {
  } catch (error) {
    next(error);
  }
};
